# Use an official Python runtime as a parent image
FROM alpine:latest

RUN apk add python3-dev && \
    python3 -m ensurepip && \
    pip3 install --upgrade pip setuptools && \
    rm -r /usr/lib/python*/ensurepip && \
    rm /usr/bin/pip && \
    ln -s /usr/bin/pip3 /usr/bin/pip

# Install PostgreSQL development files
RUN apk add postgresql-dev
