# Generated by Django 4.2 on 2023-04-28 06:28

from django.db import migrations, models
import post.utils.rename_media


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.FileField(upload_to=post.utils.rename_media.rename_media),
        ),
    ]
