# Generated by Django 4.2 on 2024-03-08 07:11

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(max_length=200, upload_to=post.models.upload_to_posts),
        ),
    ]
