# Generated by Django 4.2 on 2023-05-01 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_post_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
