# Generated by Django 4.2 on 2023-05-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_like_remove_post_shares_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
