# Generated by Django 4.2 on 2023-05-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_rename_story_id_story_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
    ]
