# Generated by Django 4.2 on 2023-06-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_presence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='converdation_id',
            new_name='conversation_id',
        ),
    ]
