# Generated by Django 4.2 on 2023-05-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_usercommunication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercommunication',
            options={'ordering': ['-updated_at']},
        ),
    ]
