# Generated by Django 4.2 on 2023-06-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_converdation_id_conversation_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.TextField(default=''),
        ),
    ]
