# Generated by Django 4.2 on 2023-05-15 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_rename_chats_chat_delete_conversations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='converdation_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
