# Generated by Django 4.2 on 2023-05-05 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_user',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
