# Generated by Django 4.2 on 2023-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
