# Generated by Django 4.2 on 2024-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='id',
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
