# Generated by Django 4.2 on 2024-03-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_interest_id_alter_interest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
